// Interface automatically generated by schemas-to-ts

import { User } from '../../../../common/schemas-to-ts/User';
import { User_Plain } from '../../../../common/schemas-to-ts/User';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Article {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    Title: string;
    Description: string;
    Content: string;
    Date: Date;
    authors?: { data: User[] };
    Slug: string;
  };
}
export interface Article_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Title: string;
  Description: string;
  Content: string;
  Date: Date;
  authors?: User_Plain[];
  Slug: string;
}

export interface Article_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Title: string;
  Description: string;
  Content: string;
  Date: Date;
  authors?: number[];
  Slug: string;
}

export interface Article_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Title: string;
  Description: string;
  Content: string;
  Date: Date;
  authors?: AdminPanelRelationPropertyModification<User_Plain>;
  Slug: string;
}
